### ISSUE TITLE
add Step component

### ISSUE THREAD

**Issue by johi** [RabbitSystems/smartgoals#7]
### Overview

Add Step component.

- The Step component can be one of five types:
  + Specific
  + Measurable
  + Attainable
  + Relevant
  + Time-specific
- According to its type, the Step component can have, a text input, a rating input or a date input.
- The Step component has a label.
- The Step has satisfaction criteria for when it is done.
  + Specific:
    * `<string>value` not empty
  + Measurable
    * `<string>value` not empty
  + Attainable
    * `<string>value` not empty
  + Relevant
    * `<string>value` is `[1..5]`
  + Time-specific
    * `<string>value` is an ISO-8601 timestamp

#### Model

Inputs:

- Properties
  + `<string>type`
  + `<string>value`
  + `<string>label`

- Actions
  + `<string>value`

State has
- `<boolean>done`
- `<string>label`
- `<string>value`
- `<string>type`

### Motivation
As a User, I want to fill out a step, in order to define my S.M.A.R.T. goal.

**Comment by Frikki** [comment]
Rethinking this, the component should be split into five distinct components, reflecting the five types:

- Specific,
- Measurable,
- Attainable,
- Relevant, and
- Time Specific.

The reason is that their values and satisfaction criteria are unique to each type. So to follow the principle of Separation of Concerns, distinct components seems to be the right thing to do.
